name: Test-Build
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: >-
          Install the newman command line utility and also install the html
          extra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Make Directory for results
        run: mkdir -p testResults
      - name: Run POSTMAN collection
        run: >
          newman run ./tests/venus_groups_01.postman_collection.json -e
          ./tests/QA.postman_environment.json -r htmlextra
          --reporter-htmlextra-export testResults/htmlreport.html
          --reporter-htmlextra-darkTheme  > testResults/runreport1.html 
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
